{{- if include "graylog.input.generateCerts.enabled" . }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: graylog-input-tls-certificate
  labels:
    app.kubernetes.io/name: graylog-input-tls-certificate
    app.kubernetes.io/component: graylog
    app.kubernetes.io/part-of: logging
  {{- if .Values.graylog.labels }}
    {{- toYaml .Values.graylog.labels | nindent 4 }}
  {{- end }}
  {{- if .Values.graylog.annotations }}
  annotations:
    {{- toYaml .Values.graylog.annotations | nindent 4 }}
  {{- end }}
spec:
  secretName: {{ default "graylog-input-cert-manager-tls" .Values.graylog.tls.input.generateCerts.secretName }}
  duration: {{ default 365 .Values.graylog.tls.input.generateCerts.duration | mul 24 }}h
  renewBefore: {{ default 15 .Values.graylog.tls.input.generateCerts.renewBefore | mul 24 }}h
  commonName: graylog-input-crt
  isCA: false
  privateKey:
    rotationPolicy: Always
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  dnsNames:
    - localhost
    - graylog-service.{{ .Release.Namespace }}.svc
    - {{ regexFind "([-a-zA-Z\\d]+\\.)+([-a-zA-Z\\d])+" (include "graylog.host" .) }}
  ipAddresses:
    - 127.0.0.1
  issuerRef:
  {{- if .Values.graylog.tls.input.generateCerts.clusterIssuerName }}
    name: {{ .Values.graylog.tls.input.generateCerts.clusterIssuerName }}
    kind: ClusterIssuer
  {{- else }}
    name: logging-ca-issuer
    kind: Issuer
  {{- end }}
    group: cert-manager.io
{{- end }}
