{{- if .Capabilities.APIVersions.Has "security.openshift.io/v1" }}
{{- if .Values.createClusterAdminEntities }}
{{- if .Values.graylog.install }}
{{- if .Values.graylog.securityResources.install }}
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
priority: 3
metadata:
  name: {{ .Values.graylog.securityResources.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.graylog.securityResources.name }}
    app.kubernetes.io/component: graylog
    app.kubernetes.io/part-of: logging
  {{- if .Values.graylog.labels }}
    {{- toYaml .Values.graylog.labels | nindent 4 }}
  {{- end }}
  {{- if .Values.graylog.annotations }}
  annotations:
    {{- toYaml .Values.graylog.annotations | nindent 4 }}
  {{- end }}
allowPrivilegedContainer: false
allowHostDirVolumePlugin: true
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
  - system:serviceaccount:{{ .Release.Namespace }}:logging-graylog
defaultAddCapabilities: []
requiredDropCapabilities: []
allowedCapabilities: []
volumes:
  - 'configMap'
  - 'emptyDir'
  - 'projected'
  - 'secret'
  - 'persistentVolumeClaim'
allowHostNetwork: false
allowHostPorts: false
allowHostPID: false
allowHostIPC: false
readOnlyRootFilesystem: false
{{- end }}
{{- end }}
{{- end }}
{{- end }}
