{{- if .Values.graylog.install }}
apiVersion: v1
kind: Secret
metadata:
  name: graylog-secret
  labels:
    app.kubernetes.io/name: graylog-secret
    app.kubernetes.io/component: graylog
    app.kubernetes.io/part-of: logging
  {{- if .Values.graylog.labels }}
    {{- toYaml .Values.graylog.labels | nindent 4 }}
  {{- end }}
  {{- if .Values.graylog.annotations }}
  annotations:
    {{- toYaml .Values.graylog.annotations | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- with .Values.graylog }}
  elasticsearchHost: {{ .elasticsearchHost | default "" | b64enc }}
  password: {{ .password | default "" | b64enc }}
  user: {{ .user | default "admin"  | b64enc }}
  {{- if .s3Archive }}
  awsAccessKey: {{ .awsAccessKey | default ""| b64enc }}
  awsSecretKey: {{ .awsSecretKey | default "" | b64enc }}
  {{- end }}
  {{- end }}
{{- end }}
