apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: logging-service-operator
  labels:
    app.kubernetes.io/name: logging-service-operator
    app.kubernetes.io/component: logging-operator
    app.kubernetes.io/part-of: logging
  {{- if .Values.labels }}
    {{- toYaml .Values.labels | nindent 4 }}
  {{- end }}
  {{- if .Values.annotations }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
  {{- end }}
rules:
  - apiGroups:
      - logging.qubership.org
    resources:
      - '*'
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
      - delete
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - services/finalizers
      - configmaps
      - secrets
      - serviceaccounts
      - persistentvolumeclaims
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
      - delete
  - apiGroups:
      - apps
    resources:
      - deployments
      - deployments/finalizers
      - daemonsets
      - statefulsets
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
      - delete
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
      - delete
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - podmonitors
    verbs:
      - create
      - update
