apiVersion: v1
kind: ServiceAccount
metadata:
  name: logging-service-operator
  labels:
    app.kubernetes.io/name: logging-service-operator
    app.kubernetes.io/component: logging-operator
    app.kubernetes.io/part-of: logging
  {{- if .Values.labels }}
    {{- toYaml .Values.labels | nindent 4 }}
  {{- end }}
  {{- if .Values.annotations }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
  {{- end }}
