{{/* Can be used only for deployment in Kubernetes <1.25 */}}
{{- if .Capabilities.APIVersions.Has "policy/v1beta1" }}
  {{- if .Values.createClusterAdminEntities }}
    {{- if .Values.fluentbit.install }}
      {{- if .Values.fluentbit.securityResources.install }}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ .Values.fluentbit.securityResources.name }}
  annotations:
    kubernetes.io/description: {{ .Values.fluentbit.securityResources.name }} psp is used for the fluentbit daemonset
  {{- if .Values.fluentbit.annotations }}
    {{- toYaml .Values.fluentbit.annotations | nindent 4 }}
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ .Values.fluentbit.securityResources.name }}
    app.kubernetes.io/component: fluentbit
    app.kubernetes.io/part-of: logging
  {{- if .Values.fluentbit.labels }}
    {{- toYaml .Values.fluentbit.labels | nindent 4 }}
  {{- end }}
spec:
  privileged: false
  allowPrivilegeEscalation: false
  # This is redundant with non-root + disallow privilege escalation,
  # but we can provide it for defense in depth.
  requiredDropCapabilities:
    - ALL
  # Allow core volume types.
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'projected'
    - 'secret'
    - 'downwardAPI'
    - 'persistentVolumeClaim'
    - 'hostPath'
  allowedHostPaths:
    - pathPrefix: "/var/log"
    - pathPrefix: "/var/lib/docker/containers"
    - pathPrefix: "/fluent-bit/etc"
      readOnly: true
  hostNetwork: true
  hostIPC: false
  hostPID: true
  runAsUser:
    # Permits the container to run with root privileges as well.
    rule: 'RunAsAny'
  seLinux:
    # This policy assumes the nodes are using AppArmor rather than SELinux.
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      # Allow adding the root group.
      - min: 0
        max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      # Allow adding the root group.
      - min: 0
        max: 65535
  readOnlyRootFilesystem: false
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
