apiVersion: v1
kind: Service
metadata:
  name: events-reader
  namespace: {{ .Release.Namespace }}
  labels:
    name: events-reader
    app.kubernetes.io/name: events-reader
    app.kubernetes.io/component: events-reader
    app.kubernetes.io/part-of: logging
    app.kubernetes.io/managed-by: logging-operator
spec:
  selector:
    name: events-reader
  ports:
    - name: events-reader
      port: 8080
      protocol: TCP
      targetPort: 8080
