{{- if .Values.createClusterAdminEntities }}
{{- if .Values.fluentbit.install }}
{{- if .Values.fluentbit.aggregator }}
{{- if .Values.fluentbit.aggregator.install }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: logging-fluentbit-aggregator-cluster-reader
  labels:
    app.kubernetes.io/name: logging-fluentbit-aggregator-cluster-reader
    app.kubernetes.io/component: fluentbit
    app.kubernetes.io/part-of: logging
  {{- if .Values.fluentbit.labels }}
    {{- toYaml .Values.fluentbit.labels | nindent 4 }}
  {{- end }}
  {{- if .Values.fluentbit.annotations }}
  annotations:
    {{- toYaml .Values.fluentbit.annotations | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: logging-fluentbit-aggregator-cluster-role
subjects:
  - kind: ServiceAccount
    name: logging-fluentbit-aggregator
    namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
