{{- if .Values.createClusterAdminEntities }}
{{- if .Values.fluentbit.install }}
{{- if .Values.fluentbit.aggregator }}
{{- if .Values.fluentbit.aggregator.install }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: logging-fluentbit-aggregator-cluster-role
  labels:
    app.kubernetes.io/name: logging-fluentbit-aggregator-cluster-role
    app.kubernetes.io/component: fluentbit
    app.kubernetes.io/part-of: logging
  {{- if .Values.fluentbit.labels }}
    {{- toYaml .Values.fluentbit.labels | nindent 4 }}
  {{- end }}
  {{- if .Values.fluentbit.annotations }}
  annotations:
    {{- toYaml .Values.fluentbit.annotations | nindent 4 }}
  {{- end }}
rules:
  {{- if $.Capabilities.APIVersions.Has "policy/v1beta1" }}
  - apiGroups:
      - policy
    resources:
      - podsecuritypolicies
    verbs:
      - use
    resourceNames:
      - {{ .Values.fluentbit.aggregator.securityResources.name }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
