{{- if .Capabilities.APIVersions.Has "security.openshift.io/v1" }}
{{- if .Values.createClusterAdminEntities }}
{{- if .Values.fluentbit.install }}
{{- if .Values.fluentbit.aggregator }}
{{- if .Values.fluentbit.aggregator.install }}
{{- if .Values.fluentbit.aggregator.securityResources.install }}
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
priority: 3
metadata:
  name: {{ .Values.fluentbit.aggregator.securityResources.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.fluentbit.aggregator.securityResources.name }}
    app.kubernetes.io/component: fluentbit
    app.kubernetes.io/part-of: logging
  {{- if .Values.fluentbit.labels }}
    {{- toYaml .Values.fluentbit.labels | nindent 4 }}
  {{- end }}
  {{- if .Values.fluentbit.annotations }}
  annotations:
    {{- toYaml .Values.fluentbit.annotations | nindent 4 }}
  {{- end }}
allowPrivilegedContainer: false
allowHostDirVolumePlugin: true
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
  - system:serviceaccount:{{ .Release.Namespace }}:logging-fluentbit-aggregator
defaultAddCapabilities: []
requiredDropCapabilities: []
allowedCapabilities: []
volumes:
  - configMap
  - secret
  - emptyDir
  - persistentVolumeClaim
allowHostNetwork: false
allowHostPorts: false
allowHostPID: false
allowHostIPC: false
readOnlyRootFilesystem: false
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
