{{- if .Values.fluentbit.install }}
{{- if .Values.fluentbit.aggregator }}
{{- if .Values.fluentbit.aggregator.install }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: logging-fluentbit-aggregator
  labels:
    app.kubernetes.io/name: logging-fluentbit-aggregator
    app.kubernetes.io/component: fluentbit
    app.kubernetes.io/part-of: logging
  {{- if .Values.fluentbit.labels }}
    {{- toYaml .Values.fluentbit.labels | nindent 4 }}
  {{- end }}
  {{- if .Values.fluentbit.annotations }}
  annotations:
    {{- toYaml .Values.fluentbit.annotations | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
