{{- if .Capabilities.APIVersions.Has "security.openshift.io/v1" }}
{{- if .Values.createClusterAdminEntities }}
{{- if .Values.fluentd.install }}
{{- if .Values.fluentd.securityResources.install }}
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
priority: 3
metadata:
  name: {{ .Values.fluentd.securityResources.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.fluentd.securityResources.name }}
    app.kubernetes.io/component: fluentd
    app.kubernetes.io/part-of: logging
  {{- if .Values.fluentd.labels }}
    {{- toYaml .Values.fluentd.labels | nindent 4 }}
  {{- end }}
  {{- if .Values.fluentd.annotations }}
  annotations:
    {{- toYaml .Values.fluentd.annotations | nindent 4 }}
  {{- end }}
allowPrivilegedContainer: {{ .Values.fluentd.securityContextPrivileged }}
allowHostDirVolumePlugin: true
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
  - system:serviceaccount:{{ .Release.Namespace }}:logging-fluentd
defaultAddCapabilities: []
requiredDropCapabilities: []
allowedCapabilities: []
volumes:
  - configMap
  - secret
  - hostPath
allowHostNetwork: false
allowHostPorts: false
allowHostPID: false
allowHostIPC: false
readOnlyRootFilesystem: false
{{- end }}
{{- end }}
{{- end }}
{{- end }}
