{{- if and .Values.fluentd.install }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: logging-fluentd
  labels:
    app.kubernetes.io/name: logging-fluentd
    app.kubernetes.io/component: fluentd
    app.kubernetes.io/part-of: logging
  {{- if .Values.fluentd.labels }}
    {{- toYaml .Values.fluentd.labels | nindent 4 }}
  {{- end }}
  {{- if .Values.fluentd.annotations }}
  annotations:
    {{- toYaml .Values.fluentd.annotations | nindent 4 }}
  {{- end }}
{{- end }}
