{{- if .Values.graylog.install }}
{{- if .Values.graylog.authProxy.install }}
{{- if eq .Values.graylog.authProxy.authType "ldap" }}
{{- with .Values.graylog.authProxy.ldap }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .bindPasswordSecret.name | default "graylog-auth-proxy-secret"}}
  labels:
    app.kubernetes.io/name: {{ .bindPasswordSecret.name | default "graylog-auth-proxy-secret" }}
    app.kubernetes.io/component: graylog
    app.kubernetes.io/part-of: logging
  {{- if $.Values.graylog.labels }}
    {{- toYaml $.Values.graylog.labels | nindent 4 }}
  {{- end }}
  {{- if $.Values.graylog.annotations }}
  annotations:
    {{- toYaml $.Values.graylog.annotations | nindent 4 }}
  {{- end }}
type: Opaque
data:
  # Double encryption because the proxy uses .htpasswd format that should contain data encrypted as Base64
  {{ .bindPasswordSecret.key | default "bindPassword" }}: {{ .bindPassword | default "" | b64enc | b64enc }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
