{
 "title": "Fluentd",
 "description": "Dashboards show main Fluentd's metrics.",
 "tags": [
  "logging",
  "fluentd"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(up,cluster)" } },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(fluentd_output_status_write_count{cluster=\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "interval",
    "label": "Sample",
    "query": "1m,2m,5m,10m,30m,1h,2h,5h,10h,1d"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(fluentd_output_status_write_count{cluster=\"$cluster\", namespace=\"$namespace\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Build Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Version",
     "type": "table",
     "description": "Fluentd version",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "fluentd_build_info{cluster=\"$cluster\", namespace=\"$namespace\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pods Running In DaemonSet",
   "type": "timeseries",
   "description": "Number of running pods displayed during the specified time",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Pods Running",
     "expr": "kube_daemonset_status_number_ready{cluster=\"$cluster\", exported_namespace=\"$namespace\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "ready",
     "query": "SELECT  last(\"value\") FROM /^logging\\.pods_running$/ WHERE namespace = '$namespace' AND service_name = 'logging-fluentd' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Pods Running",
     "expr": "kube_daemonset_status_number_unavailable{cluster=\"$cluster\", exported_namespace=\"$namespace\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "unavailable",
     "query": "SELECT  last(\"value\") FROM /^logging\\.pods_running$/ WHERE namespace = '$namespace' AND service_name = 'logging-fluentd' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Plugins Retry Count",
   "type": "timeseries",
   "description": "Number of retry to restart plugin displayed during the specified time. A large number of retry is bad",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$2.$tag_pod",
     "expr": "fluentd_output_status_retry_count{cluster=\"$cluster\", namespace=\"$namespace\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{type}}: {{plugin_id}}",
     "query": "SELECT last(\"value\") FROM /^logging\\.plugins\\.(.+)\\.retry_count$/ WHERE namespace = '$namespace' AND service_name = 'logging-fluentd' AND $timeFilter GROUP BY time($__interval), \"pod\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Fluentd",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Plugins Buffer Queue Length",
   "type": "timeseries",
   "description": "Buffer queue length of plugins displayed during the specified time.\nA constantly growing buffer is bad",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$2.$tag_pod",
     "expr": "sum by (hostname) (fluentd_output_status_queue_byte_size{cluster=\"$cluster\", namespace=\"$namespace\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{hostname}}",
     "query": "buffer_queue_length",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Plugins Buffer Total Queued Size",
   "type": "timeseries",
   "description": "Total buffer queue size of plugins displayed during the specified time.\nA constantly growing buffer is bad",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "$2.$tag_pod",
     "expr": "sum by (hostname) (fluentd_output_status_buffer_total_bytes{cluster=\"$cluster\", namespace=\"$namespace\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{hostname}}",
     "query": "SELECT last(\"value\") FROM /^logging\\.plugins\\.(.+)\\.buffer_total_queued_size$/  WHERE namespace = '$namespace' AND service_name = 'logging-fluentd' AND $timeFilter GROUP BY time($__interval), pod fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Resources Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU Usage $pod",
     "type": "timeseries",
     "description": "Shows CPU usage per container in pod against resource requests and limits",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
     "repeat": "pod",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(sum by (namespace, pod, container)(\r\nrate(container_cpu_usage_seconds_total{cluster=\"$cluster\",namespace=\"$namespace\", pod=\"$pod\", container!~\"POD|\", name!=\"\", image!=\"\"}[2m]))) by (pod,container)",
       "legendFormat": "usage: {{container}}"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{cluster=\"$cluster\", exported_namespace=\"$namespace\", exported_pod=\"$pod\", resource=\"cpu\"}) by (exported_pod,container)\n",
       "legendFormat": "requests: {{ container }}"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", cluster=\"$cluster\",exported_namespace=\"$namespace\", exported_pod=\"$pod\"}) by (exported_pod,container)\n",
       "legendFormat": "limits: {{ container }}"
      }
     ]
    },
    {
     "title": "Memory Usage $pod",
     "type": "timeseries",
     "description": "Shows memory usage per container in pod against resource requests and limits",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
     "repeat": "pod",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container!~\"POD|\", container!~\"POD|\", image!=\"\"}) by (container)",
       "legendFormat": "usage: {{container}}"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", cluster=\"$cluster\", exported_namespace=\"$namespace\", exported_pod=\"$pod\"}) by(container)\n",
       "legendFormat": "requests: {{ container }}"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", cluster=\"$cluster\", exported_namespace=\"$namespace\", exported_pod=\"$pod\"}) by(container)\n",
       "legendFormat": "limits: {{ container }}"
      },
      {
       "expr": "sum(container_memory_rss{cluster=\"$cluster\", namespace=\"$namespace\", pod=\"$pod\", container!=\"POD\", container!=\"\", image=~\".*\"}) by (container)\n",
       "legendFormat": "rss: {{ container }}"
      }
     ]
    },
    {
     "title": "Receive/Transmit Bandwidth $pod",
     "type": "timeseries",
     "description": "Shows network traffic in bytes per second for the pod",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
     "repeat": "pod",
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_bytes_total{cluster=\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\"}[2m])) by (pod)",
       "legendFormat": "receive"
      },
      {
       "expr": "sum(irate(container_network_transmit_bytes_total{cluster=\"$cluster\",namespace=~\"$namespace\", pod=~\"$pod\"}[2m])) by (pod)",
       "legendFormat": "transmit"
      }
     ]
    }
   ]
  }
 ]
}