{
 "title": "Graylog / Server metrics (Kubernetes)",
 "description": "Dashboard for Graylog Metrics collected by Prometheus",
 "tags": [
  "k8s",
  "graylog"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "cluster", "query": { "query": "label_values(up, cluster)" } },
   {
    "name": "graylog_namespace",
    "label": "Graylog namespace",
    "query": {
     "query": "label_values(org_graylog2_buffers_input_size{cluster=\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "fluentd_namespace",
    "label": "Fluentd namespace",
    "query": {
     "query": "label_values(fluentd_output_status_write_count{cluster=\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "elastic_namespace",
    "label": "Elastic Namespace",
    "query": {
     "query": "label_values(elasticsearch_cluster_health_status_code{cluster=\"$cluster\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Graylog Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Graylog Version",
   "type": "stat",
   "description": "Graylog version",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "group (kube_statefulset_labels{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}) by (label_app_kubernetes_io_version)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Graylog Service Status",
   "type": "stat",
   "description": "Shows if Graylog service is ready",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{cluster=\"$cluster\", container=~\"graylog\"} == 1"
    }
   ]
  },
  {
   "title": "Elastic Cluster Status",
   "type": "stat",
   "description": "Shows if Elastic cluster is running. \nPossible values: Up, Degraded, Failed",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_status_code{cluster=\"$cluster\", namespace=\"$elastic_namespace\"}) by (host)",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Buffers usage",
   "type": "stat",
   "description": "Show buffer usage. How much messages Graylog keep in input and output buffers.",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "org_graylog2_buffers_input_usage{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
     "legendFormat": "In"
    },
    {
     "expr": "org_graylog2_buffers_output_usage{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "stat",
   "description": "Show Graylog throughput. How much Graylog process messages from Fluentd to ElasticSearch.",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "org_graylog2_throughput_input_1_sec_rate{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
     "legendFormat": "In"
    },
    {
     "expr": "org_graylog2_throughput_output_1_sec_rate{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Error rate, 5m",
   "type": "stat",
   "description": "Show total errors messages (for all log levels)  which occurs in Graylog itself.",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(org_apache_logging_log4j_core_Appender_all_total[5m])"
    }
   ]
  },
  {
   "title": "Journal utilization",
   "type": "gauge",
   "description": "Show Graylog journal utilization. Graylog use journal as temporally storage of received messages which have not yet been processed by ElastiSearch.\nHigh journal utilization shows that ElasticSearch cannot process the input stream fast enough.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "org_graylog2_journal_utilization_ratio{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Utilization",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Elastic Nodes",
   "type": "timeseries",
   "description": "Shows the count of up and down nodes",
   "gridPos": { "h": 5, "w": 10, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "min(elasticsearch_cluster_health_number_of_nodes{cluster=\"$cluster\", namespace=\"$elastic_namespace\"}) by (host)",
     "legendFormat": "Up"
    },
    {
     "expr": "scalar(elasticsearch_cluster_health_total_number_of_nodes{cluster=\"$cluster\", namespace=\"$elastic_namespace\"}) - (min(elasticsearch_cluster_health_number_of_nodes{cluster=\"$cluster\", namespace=\"$elastic_namespace\"}) by (host))",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "title": "Fluentd",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Up Fluentd",
     "type": "stat",
     "description": "Shows count of working fluentd nodes",
     "gridPos": { "h": 8, "w": 2, "x": 0, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(up{container=~\".*fluentd\"} == 1) or vector(0)",
       "legendFormat": "Up"
      }
     ]
    },
    {
     "title": "Fluentd Output Status Write Count",
     "type": "timeseries",
     "description": "Show a total count of output messages which were collected by fluentd pods, by each fluentd pod",
     "gridPos": { "h": 8, "w": 11, "x": 2, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(fluentd_output_status_write_count{cluster=\"$cluster\", namespace=\"$fluentd_namespace\"}) by (hostname)",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Fluentd Input Status Records",
     "type": "timeseries",
     "description": "Show a total count of input messages in fluentd pods, by each fluentd pod. If Fluentd only read log files and send messages this graph can show empty values",
     "gridPos": { "h": 8, "w": 11, "x": 13, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(fluentd_input_status_num_records_total{cluster=\"$cluster\", namespace=\"$fluentd_namespace\"}) by (hostname) or vector(0)",
       "legendFormat": "{{ hostname }}"
      }
     ]
    },
    {
     "title": "Down Fluentd",
     "type": "stat",
     "description": "Shows count of currently not working fluentd nodes",
     "gridPos": { "h": 8, "w": 2, "x": 0, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(up{container=~\".*fluentd\"} == 0) or vector(0)",
       "legendFormat": "Up"
      }
     ]
    },
    {
     "title": "Maximum Buffer Length",
     "type": "timeseries",
     "description": "Shows the maximum buffer length in last 1 min\n\nNote: if the value is increasing,  Fluentd cannot flush the buffer to the destination. Thus you will lose the data once the buffer becomes full",
     "gridPos": { "h": 8, "w": 11, "x": 2, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max_over_time(fluentd_output_status_buffer_queue_length[1m])",
       "legendFormat": "{{hostname}}"
      }
     ]
    },
    {
     "title": "Fluentd Maximum Buffer Bytes",
     "type": "timeseries",
     "description": "Shows the maximum buffer bytes in last 1 min\n\nNote: if the value is increasing,  Fluentd cannot flush the buffer to the destination. Thus you will lose the data once the buffer becomes full",
     "gridPos": { "h": 8, "w": 11, "x": 13, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "max_over_time(fluentd_output_status_buffer_total_bytes{cluster=\"$cluster\", namespace=\"$fluentd_namespace\"}[1m])",
       "legendFormat": "{{ hostname }}"
      }
     ]
    },
    {
     "title": "Fluentd emit number per sec",
     "type": "timeseries",
     "description": "Shows the count of emit count per sec",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(fluentd_output_status_emit_count{cluster=\"$cluster\", namespace=\"$fluentd_namespace\"}[5m])) by (hostname)",
       "legendFormat": "{{hostname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "ElasticSearch Indexes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Indices size",
     "type": "timeseries",
     "description": "The size of data stored in indices",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(elasticsearch_clusterstats_indices_store_size_in_bytes) by (namespace, cluster_name)",
       "legendFormat": "{{ namespace }}: {{ cluster_name }}"
      }
     ]
    },
    {
     "title": "Count of indices",
     "type": "timeseries",
     "description": "Shows count of indices in the namespace",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(elasticsearch_clusterstats_indices_count) by (namespace, cluster_name)",
       "legendFormat": "{{ namespace }}: {{ cluster_name }}"
      }
     ]
    },
    {
     "title": "Count of documents",
     "type": "timeseries",
     "description": "Shows count of documents on node in the namespace",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(elasticsearch_indices_docs_count) by (node_name)",
       "legendFormat": "{{node_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Messages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Messages received",
     "type": "timeseries",
     "description": "Show Graylog throughput. How much Graylog process messages from Fluentd to ElasticSearch.\n`Messages append to disk` means how many messages append to journal.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "org_graylog2_throughput_input_1_sec_rate{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Messages in",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "org_graylog2_journal_append_1_sec_rate{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
       "legendFormat": "Messages appended to disk"
      },
      {
       "expr": "org_graylog2_throughput_output_1_sec_rate{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
       "legendFormat": "Messages out"
      }
     ]
    }
   ]
  },
  {
   "title": "Buffers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Graylog Input Buffer",
     "type": "timeseries",
     "description": "Show how many messages Graylog store in input buffer.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "org_graylog2_buffers_input_size{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Input buffer size",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "org_graylog2_buffers_input_usage{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
       "legendFormat": "Input buffer usage"
      }
     ]
    },
    {
     "title": "Graylog Process Buffer",
     "type": "timeseries",
     "description": "Show how many messages Graylog store in process buffer.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "org_graylog2_buffers_process_size{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Process buffer size",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "org_graylog2_buffers_process_usage{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
       "legendFormat": "Process buffer usage"
      }
     ]
    },
    {
     "title": "Graylog Output Buffer",
     "type": "timeseries",
     "description": "Show how many messages Graylog store in output buffer.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "org_graylog2_buffers_output_size{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Output buffer size",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "org_graylog2_buffers_output_usage{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
       "legendFormat": "Output buffer usage"
      }
     ]
    }
   ]
  },
  {
   "title": "Input and Output streams",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Streams incoming messages rate, sum by inputs, msg/s",
     "type": "timeseries",
     "description": "Shows the count of incoming messages of streams",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum({__name__=~\"org_graylog2_plugin_streams_Stream_.*_incomingMessages_1_sec_rate\", cluster=\"$cluster\", namespace=\"$graylog_namespace\"})",
       "legendFormat": "Incoming messages"
      }
     ]
    },
    {
     "title": "Elastic Search Output Rate",
     "type": "timeseries",
     "description": "Shows rate of processing output records",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(org_graylog2_outputs_ElasticSearchOutput_processTime_count{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}[5m])",
       "legendFormat": "ElasticSearch Output"
      },
      {
       "expr": "rate(org_graylog2_outputs_BlockingBatchedESOutput_processTime_count{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}[5m])",
       "legendFormat": "Blocking Batched ElasticSearch Output"
      }
     ]
    },
    {
     "title": "Streams incoming messages, sum by inputs, avg msg/s",
     "type": "timeseries",
     "description": "Shows the count of incoming messages of streams",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate({__name__=~\"org_graylog2_plugin_streams_Stream_.*_incomingMessages_total\", cluster=\"$cluster\", namespace=\"$graylog_namespace\"}[1m]))",
       "legendFormat": "Incoming messages"
      }
     ]
    },
    {
     "title": "GELF parse time, sum by input",
     "type": "timeseries",
     "description": "Shows summary for GELF parsing time by Graylog for all inputs.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(rate({__name__=~\"org_graylog2_inputs_codecs_GelfCodec_.*_parseTime_count\", cluster=\"$cluster\", namespace=\"$graylog_namespace\"}[1m]))",
       "legendFormat": "GELF parse time"
      }
     ]
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Journal utilization",
     "type": "gauge",
     "description": "Show Graylog journal utilization. Graylog use journal as temporally storage of received messages which have not yet been processed by ElastiSearch.\nHigh journal utilization shows that ElasticSearch cannot process the input stream fast enough.",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "org_graylog2_journal_utilization_ratio{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Utilization",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Graylog Journal Size",
     "type": "timeseries",
     "description": "Show Graylog journal size and it limit.",
     "gridPos": { "h": 7, "w": 8, "x": 3, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "org_graylog2_journal_size_limit{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Limit",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "org_graylog2_journal_size{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
       "legendFormat": "Usage"
      }
     ]
    },
    {
     "title": "Journal Append and Read",
     "type": "timeseries",
     "description": "Show journal append and read sizes in bytes. In a normal situation append and read should be roughly the same.",
     "gridPos": { "h": 7, "w": 13, "x": 11, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "org_graylog2_journal_append_1_sec_rate{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Append",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "org_graylog2_journal_read_1_sec_rate{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
       "legendFormat": "Read"
      }
     ]
    },
    {
     "title": "Journal Uncommitted, Segments",
     "type": "timeseries",
     "description": "Show how much uncommitted messages in journal and how much segments in journal",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "org_graylog2_journal_entries_uncommitted{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Uncommitted",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "org_graylog2_journal_segments{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
       "legendFormat": "Segments"
      }
     ]
    },
    {
     "title": "Error rate",
     "type": "timeseries",
     "description": "Show error rate in logs of Graylog process",
     "gridPos": { "h": 7, "w": 16, "x": 8, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(org_apache_logging_log4j_core_Appender_debug_total[5m])",
       "legendFormat": "Debug"
      },
      {
       "expr": "rate(org_apache_logging_log4j_core_Appender_error_total[5m])",
       "legendFormat": "Error"
      },
      {
       "expr": "rate(org_apache_logging_log4j_core_Appender_fatal_total[5m])",
       "legendFormat": "Fatal"
      },
      {
       "expr": "rate(org_apache_logging_log4j_core_Appender_info_total[5m])",
       "legendFormat": "Info"
      },
      {
       "expr": "rate(org_apache_logging_log4j_core_Appender_trace_total[5m])",
       "legendFormat": "Trace"
      },
      {
       "expr": "rate(org_apache_logging_log4j_core_Appender_warn_total[5m])",
       "legendFormat": "Warning"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "description": "Shows CPU usage per container in pod against resource requests and limits",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(sum by (namespace, pod, container) (\rrate(container_cpu_usage_seconds_total{cluster=\"$cluster\", namespace=\"$graylog_namespace\", container!=\"POD\", container!=\"\", name!=\"\", image!=\"\", pod=~\".*graylog.*\"}[1m]))) by (pod,container) * 1000",
       "legendFormat": "usage: {{ container }}"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{cluster=\"$cluster\", exported_namespace=\"$graylog_namespace\", exported_pod=~\".*graylog.*\"}) by (exported_pod,container) * 1000",
       "legendFormat": "requests: {{ container }}"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_cpu_cores{cluster=\"$cluster\",exported_namespace=\"$graylog_namespace\", exported_pod=~\".*graylog.*\"}) by (exported_pod,container) * 1000",
       "legendFormat": "limits: {{ container }}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "JVM Heap",
     "type": "timeseries",
     "description": "Shows the heap JVM memory  used volume",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_heap_used{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_heap_max{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
       "legendFormat": "Limit"
      },
      {
       "expr": "jvm_memory_heap_committed{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
       "legendFormat": "Committed"
      }
     ]
    },
    {
     "title": "JVM Non-Heap",
     "type": "timeseries",
     "description": "Shows the non-heap JVM memory  used volume",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_non_heap_used{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_non_heap_max{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
       "legendFormat": "Limit"
      },
      {
       "expr": "jvm_memory_non_heap_committed{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
       "legendFormat": "Committed"
      }
     ]
    },
    {
     "title": "JVM Total",
     "type": "timeseries",
     "description": "Shows the amount of memory \n - used\n - committed to use\n -  max that can be used",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_total_used{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_total_max{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
       "legendFormat": "Limit"
      },
      {
       "expr": "jvm_memory_total_committed{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
       "legendFormat": "Committed"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Survivor Space",
     "type": "timeseries",
     "description": "Show heap memory usage for Survivor Space space",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_memory_pools_Par_Survivor_Space_committed{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
       "legendFormat": "committed"
      },
      {
       "expr": "jvm_memory_pools_Par_Survivor_Space_max{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
       "legendFormat": "max"
      },
      {
       "expr": "jvm_memory_pools_Par_Survivor_Space_used{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
       "legendFormat": "used"
      }
     ]
    },
    {
     "title": "Eden Space",
     "type": "timeseries",
     "description": "Show heap memory usage for Eden Space space",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_memory_pools_Par_Eden_Space_committed{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
       "legendFormat": "committed"
      },
      {
       "expr": "jvm_memory_pools_Par_Eden_Space_max{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
       "legendFormat": "max"
      },
      {
       "expr": "jvm_memory_pools_Par_Eden_Space_used{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
       "legendFormat": "used"
      }
     ]
    },
    {
     "title": "Old Gen",
     "type": "timeseries",
     "description": "Show heap memory usage for Old Gen space",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_memory_pools_CMS_Old_Gen_committed{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
       "legendFormat": "committed"
      },
      {
       "expr": "jvm_memory_pools_CMS_Old_Gen_max{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
       "legendFormat": "max"
      },
      {
       "expr": "jvm_memory_pools_CMS_Old_Gen_used{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
       "legendFormat": "used"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Non-Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Code Cache",
     "type": "timeseries",
     "description": "Show non-heap memory usage for Code Cache space",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_memory_pools_Code_Cache_committed{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
       "legendFormat": "committed"
      },
      {
       "expr": "jvm_memory_pools_Code_Cache_max{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
       "legendFormat": "max"
      },
      {
       "expr": "jvm_memory_pools_Code_Cache_used{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
       "legendFormat": "used"
      }
     ]
    },
    {
     "title": "Compressed Class Space",
     "type": "timeseries",
     "description": "Show non-heap memory usage for Compressed Class space",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_memory_pools_Compressed_Class_Space_committed{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
       "legendFormat": "committed"
      },
      {
       "expr": "jvm_memory_pools_Compressed_Class_Space_max{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
       "legendFormat": "max"
      },
      {
       "expr": "jvm_memory_pools_Compressed_Class_Space_used{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
       "legendFormat": "used"
      }
     ]
    },
    {
     "title": "Metaspace",
     "type": "timeseries",
     "description": "Show non-heap memory usage for Metaspace",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_memory_pools_Metaspace_committed{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
       "legendFormat": "committed"
      },
      {
       "expr": "jvm_memory_pools_Metaspace_max{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
       "legendFormat": "max"
      },
      {
       "expr": "jvm_memory_pools_Metaspace_used{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
       "legendFormat": "used"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Threads states",
     "type": "timeseries",
     "description": "Show threads by them states",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_threads_blocked_count{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
       "legendFormat": "Blocked"
      },
      {
       "expr": "jvm_threads_deadlock_count{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
       "legendFormat": "Deadlock"
      },
      {
       "expr": "jvm_threads_new_count{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
       "legendFormat": "New"
      },
      {
       "expr": "jvm_threads_runnable_count{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
       "legendFormat": "Runnable"
      },
      {
       "expr": "jvm_threads_terminated_count{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
       "legendFormat": "Terminated"
      },
      {
       "expr": "jvm_threads_timed_waiting_count{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
       "legendFormat": "Timed waiting"
      },
      {
       "expr": "jvm_threads_waiting_count{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
       "legendFormat": "Waiting"
      }
     ]
    },
    {
     "title": "Threads used",
     "type": "timeseries",
     "description": "Show total threads count",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_threads_count{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
       "legendFormat": "Total"
      },
      {
       "expr": "jvm_threads_daemon_count{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
       "legendFormat": "Daemon"
      },
      {
       "expr": "jvm_threads_runnable_count{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
       "legendFormat": "Runnable"
      }
     ]
    },
    {
     "title": "New threads, rpm",
     "type": "timeseries",
     "description": "Show how much threads created, show as rate in second",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "round(rate(jvm_threads_count{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}[$__rate_interval])*60)",
       "legendFormat": "started"
      }
     ]
    },
    {
     "title": "Buffers count",
     "type": "timeseries",
     "description": "Show total JVM buffers counts for direct and mapped buffers",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_buffers_mapped_count{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
       "legendFormat": "mapped"
      },
      {
       "expr": "jvm_buffers_direct_count{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
       "legendFormat": "direct"
      }
     ]
    },
    {
     "title": "Used buffers",
     "type": "timeseries",
     "description": "Show JVM buffers usage in bytes",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_buffers_mapped_used{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
       "legendFormat": "mapped"
      },
      {
       "expr": "jvm_buffers_direct_used{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
       "legendFormat": "direct"
      }
     ]
    },
    {
     "title": "Direct buffers",
     "type": "timeseries",
     "description": "Show JVM direct buffer usage and it capacity in bytes",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_buffers_direct_capacity{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
       "legendFormat": "capacity"
      },
      {
       "expr": "jvm_buffers_direct_used{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
       "legendFormat": "used"
      }
     ]
    },
    {
     "title": "Mapped buffers",
     "type": "timeseries",
     "description": "Show JVM mapped buffer usage and it capacity in bytes",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 38 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_buffers_mapped_capacity{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
       "legendFormat": "capacity"
      },
      {
       "expr": "jvm_buffers_mapped_used{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
       "legendFormat": "used"
      }
     ]
    }
   ]
  },
  {
   "title": "Garbage Collection (pause times and collection statistics)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Collections",
     "type": "timeseries",
     "description": "Show how much operations execute GC to collect garbage in second for selected time period and interval minimum 1m",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(jvm_gc_ConcurrentMarkSweep_count{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}[$__rate_interval])",
       "legendFormat": "ConcurrentMarkSweep"
      },
      {
       "expr": "rate(jvm_gc_ParNew_count{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}[$__rate_interval])",
       "legendFormat": "ParNew"
      }
     ]
    },
    {
     "title": "Pause durations, avg per collection",
     "type": "timeseries",
     "description": "Show JVM pause duration during GC for each collection",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(jvm_gc_ConcurrentMarkSweep_time{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}[$__rate_interval]) / rate(jvm_gc_ConcurrentMarkSweep_count{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}[$__rate_interval])",
       "legendFormat": "avg ConcurrentMarkSweep"
      },
      {
       "expr": "rate(jvm_gc_ParNew_time{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}[$__rate_interval]) / rate(jvm_gc_ParNew_count{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}[$__rate_interval])",
       "legendFormat": "avg ParNew"
      }
     ]
    },
    {
     "title": "Pause Durations, total per minute",
     "type": "timeseries",
     "description": "Show total JVM pause duration rate during GC for 1m interval",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "increase(jvm_gc_ConcurrentMarkSweep_time{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}[1m])",
       "legendFormat": "total ConcurrentMarkSweep"
      },
      {
       "expr": "increase(jvm_gc_ParNew_time{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}[1m])",
       "legendFormat": "total ParNew"
      }
     ]
    }
   ]
  },
  {
   "title": "Garbage Collection (Last GC)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total GC Counts from start",
     "type": "stat",
     "description": "Total GC events counted from process start",
     "gridPos": { "h": 9, "w": 5, "x": 0, "y": 24 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "jvm_gc_ParNew_count{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
       "legendFormat": "ParNew"
      },
      {
       "expr": "jvm_gc_ConcurrentMarkSweep_count{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
       "legendFormat": "ConcurrentMarkSweep"
      }
     ]
    },
    {
     "title": "Memory Pool After GC (Heap)",
     "type": "timeseries",
     "description": "Show memory pool (heap) size in bytes after last GC. Graph show in stack mode.",
     "gridPos": { "h": 9, "w": 19, "x": 5, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_pools_CMS_Old_Gen_used_after_gc{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
       "legendFormat": "Old Gen"
      },
      {
       "expr": "jvm_memory_pools_Par_Survivor_Space_used_after_gc{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
       "legendFormat": "Survivor Space"
      },
      {
       "expr": "jvm_memory_pools_Par_Eden_Space_used_after_gc{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
       "legendFormat": "Eden Space"
      }
     ]
    }
   ]
  },
  {
   "title": "Classloading",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Classes loaded / unloaded",
     "type": "timeseries",
     "description": "Shows count of classes loaded by class loader",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_cl_loaded{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
       "legendFormat": "Classes loaded"
      },
      {
       "expr": "jvm_cl_unloaded{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}",
       "legendFormat": "Classes unloaded"
      }
     ]
    },
    {
     "title": "Class delta",
     "type": "timeseries",
     "description": "Shows delta of loaded classes count ",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(jvm_cl_loaded{cluster=\"$cluster\", namespace=\"$graylog_namespace\"}[2m])",
       "legendFormat": "delta-2m"
      }
     ]
    }
   ]
  }
 ]
}