kind: Service
apiVersion: v1
metadata:
  name: logging-fluentbit-aggregator
  namespace: {{ .Release.Namespace }}
  labels:
    name: logging-fluentbit-aggregator
    app.kubernetes.io/name: logging-fluentbit-aggregator
    app.kubernetes.io/component: fluentbit
    app.kubernetes.io/part-of: logging
    app.kubernetes.io/managed-by: logging-operator
    component: logging-fluentbit-aggregator
{{- if .Values.OpenshiftDeploy }}
    provider: openshift
{{- else }}
    provider: kubernetes
{{- end }}
spec:
  ports:
    - name: logging-fluentbit
      protocol: TCP
      port: 2020
      targetPort: 2020
    - name: logging-fluentbit-aggregator
      protocol: TCP
      port: 24224
      targetPort: 24224
  selector:
    name: logging-fluentbit-aggregator
{{- if .Values.OpenshiftDeploy }}
    provider: openshift
{{- else }}
    provider: kubernetes
{{- end }}
  type: ClusterIP
