kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: logging-fluentbit-forwarder
  namespace: {{ .Release.Namespace }}
  labels:
    name: logging-fluentbit-forwarder
    app.kubernetes.io/name: logging-fluentbit-forwarder
    app.kubernetes.io/component: fluentbit
    app.kubernetes.io/part-of: logging
    app.kubernetes.io/managed-by: logging-operator
    component: logging-fluentbit-forwarder
{{- if .Values.OpenshiftDeploy }}
    provider: openshift
{{- else }}
    provider: kubernetes
{{- end }}
    kubernetes.io/cluster-service: "true"
spec:
  minReadySeconds: 60
  selector:
    matchLabels:
      component: logging-fluentbit-forwarder
{{- if .Values.OpenshiftDeploy }}
      provider: openshift
{{- else }}
      provider: kubernetes
{{- end }}
  template:
    metadata:
      name: logging-fluentbit-forwarder
      labels:
        name: logging-fluentbit-forwarder
        app.kubernetes.io/name: logging-fluentbit-forwarder
        app.kubernetes.io/component: fluentbit
        app.kubernetes.io/part-of: logging
        app.kubernetes.io/managed-by: logging-operator
        component: logging-fluentbit-forwarder
{{- if .Values.OpenshiftDeploy }}
        provider: openshift
{{- else }}
        provider: kubernetes
{{- end }}
        kubernetes.io/cluster-service: "true"
    spec:
      volumes:
{{- if eq .Values.ContainerRuntimeType "docker" }}
{{- if ne .Values.OSKind "ubuntu" }}
        - name: sysconfigdocker
          hostPath:
            path: "/etc/sysconfig/docker"
            type: "FileOrCreate"
{{- end }}
        - name: dockerdaemon
          hostPath:
            path: "/etc/docker/daemon.json"
            type: "FileOrCreate"
        - name: dockerhostname
          hostPath:
            path: "/etc/hostname"
            type: "FileOrCreate"
        - name: varlibdockercontainers
          hostPath:
            path: "/var/lib/docker/containers"
            type: ""
{{- end }}
        - name: varlog
          hostPath:
            path: /var/log
            type: ''
        - name: config
          configMap:
            name: logging-fluentbit-forwarder
            defaultMode: 420
{{- if .Values.Fluentbit.TLS }}
{{- if and .Values.Fluentbit.TLS.GenerateCerts .Values.Fluentbit.TLS.GenerateCerts.Enabled }}
        - name: tls-ca
          secret:
            secretName: {{ .Values.Fluentbit.TLS.GenerateCerts.SecretName }}
            defaultMode: 420 # RW grants for config map files
        - name: tls-cert
          secret:
            secretName: {{ .Values.Fluentbit.TLS.GenerateCerts.SecretName }}
            defaultMode: 420 # RW grants for config map files
        - name: tls-key
          secret:
            secretName: {{ .Values.Fluentbit.TLS.GenerateCerts.SecretName }}
            defaultMode: 420 # RW grants for config map files
{{- else }}
{{- if and .Values.Fluentbit.TLS.CA .Values.Fluentbit.TLS.CA.SecretName .Values.Fluentbit.TLS.CA.SecretKey }}
        - name: tls-ca
          secret:
            secretName: {{ .Values.Fluentbit.TLS.CA.SecretName }}
            defaultMode: 420 # RW grants for config map files
{{- end }}
{{- if and .Values.Fluentbit.TLS.Cert .Values.Fluentbit.TLS.Cert.SecretName .Values.Fluentbit.TLS.Cert.SecretKey }}
        - name: tls-cert
          secret:
            secretName: {{ .Values.Fluentbit.TLS.Cert.SecretName }}
            defaultMode: 420 # RW grants for config map files
{{- end }}
{{- if and .Values.Fluentbit.TLS.Key .Values.Fluentbit.TLS.Key.SecretName .Values.Fluentbit.TLS.Key.SecretKey }}
        - name: tls-key
          secret:
            secretName: {{ .Values.Fluentbit.TLS.Key.SecretName }}
            defaultMode: 420 # RW grants for config map files
{{- end }}
{{- end }}
{{- end }}
      containers:
        - name: configmap-reload
          image: {{ .Values.Fluentbit.ConfigmapReload.DockerImage }}
          args:
            - --volume-dir=/fluent-bit/etc
            - --webhook-url=http://localhost:2020/api/v2/reload
            - --webhook-retries=5
          volumeMounts:
            - mountPath: /fluent-bit/etc
              name: config
              readOnly: true
          {{- if .Values.Fluentbit.ConfigmapReload.Resources }}
          resources:
            limits:
              cpu: {{ resIndex .Values.Fluentbit.ConfigmapReload.Resources.Limits "cpu" }}
              memory: {{ resIndex .Values.Fluentbit.ConfigmapReload.Resources.Limits "memory" }}
            requests:
              cpu: {{ resIndex .Values.Fluentbit.ConfigmapReload.Resources.Requests "cpu" }}
              memory: {{ resIndex .Values.Fluentbit.ConfigmapReload.Resources.Requests "memory" }}
          {{- end }}
          ports:
            - containerPort: 9533
              name: reload-metrics
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
        - name: logging-fluentbit-forwarder
          image: {{ .Values.Fluentbit.DockerImage }}
          securityContext:
            privileged: {{ .Values.Fluentbit.SecurityContextPrivileged }}
          ports:
            - containerPort: 2020
              protocol: TCP
              name: "http"
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
{{- if .Values.Fluentbit.Resources }}
          resources:
            limits:
              cpu: {{ resIndex .Values.Fluentbit.Resources.Limits "cpu" }}
              memory: {{ resIndex .Values.Fluentbit.Resources.Limits "memory" }}
            requests:
              cpu: {{ resIndex .Values.Fluentbit.Resources.Requests "cpu" }}
              memory: {{ resIndex .Values.Fluentbit.Resources.Requests "memory" }}
{{- end }}
          volumeMounts:
{{- if eq .Values.ContainerRuntimeType "docker" }}
{{- if ne .Values.OSKind "ubuntu" }}
            - mountPath: /etc/sysconfig/docker
              name: sysconfigdocker
              readOnly: true
{{- end }}
            - mountPath: /etc/docker/daemon.json
              name: dockerdaemon
              readOnly: true
            - mountPath: /etc/docker-hostname
              name: dockerhostname
              readOnly: true
            - mountPath: /var/lib/docker/containers
              name: varlibdockercontainers
              readOnly: true
{{- end }}
            - name: varlog
              mountPath: /var/log
            - name: config
              readOnly: true
              mountPath: /fluent-bit/etc
{{- if .Values.Fluentbit.TLS }}
{{- if and .Values.Fluentbit.TLS.GenerateCerts .Values.Fluentbit.TLS.GenerateCerts.Enabled }}
            - mountPath: /fluent-bit/tls/ca.crt
              name: tls-ca
              readOnly: true
              subPath: "ca.crt"
            - mountPath: /fluent-bit/tls/tls.crt
              name: tls-cert
              readOnly: true
              subPath: "tls.crt"
            - mountPath: /fluent-bit/tls/tls.key
              name: tls-key
              readOnly: true
              subPath: "tls.key"
{{- else }}
{{- if and .Values.Fluentbit.TLS.CA .Values.Fluentbit.TLS.CA.SecretName .Values.Fluentbit.TLS.CA.SecretKey }}
            - mountPath: /fluent-bit/tls/ca.crt
              name: tls-ca
              readOnly: true
              subPath: {{ .Values.Fluentbit.TLS.CA.SecretKey }}
{{- end }}
{{- if and .Values.Fluentbit.TLS.Cert .Values.Fluentbit.TLS.Cert.SecretName .Values.Fluentbit.TLS.Cert.SecretKey }}
            - mountPath: /fluent-bit/tls/tls.crt
              name: tls-cert
              readOnly: true
              subPath: {{ .Values.Fluentbit.TLS.Cert.SecretKey }}
{{- end }}
{{- if and .Values.Fluentbit.TLS.Key .Values.Fluentbit.TLS.Key.SecretName .Values.Fluentbit.TLS.Key.SecretKey }}
            - mountPath: /fluent-bit/tls/tls.key
              name: tls-key
              readOnly: true
              subPath: {{ .Values.Fluentbit.TLS.Key.SecretKey }}
{{- end }}
{{- end }}
{{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: 2020
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 2020
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      terminationGracePeriodSeconds: 30
      serviceAccountName: logging-fluentbit
      schedulerName: default-scheduler
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  minReadySeconds: 60
