apiVersion: v1
kind: ServiceAccount
metadata:
  name: logging-graylog
  namespace: {{ .Release.Namespace }}
  labels:
    name: logging-graylog
    app.kubernetes.io/name: logging-graylog
    app.kubernetes.io/component: graylog
    app.kubernetes.io/part-of: logging
    app.kubernetes.io/managed-by: logging-operator