{{- if .Values.integrationTests.install }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.integrationTests.service.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.integrationTests.service.name }}
    app.kubernetes.io/component: integration-tests
    app.kubernetes.io/part-of: logging
  {{- if .Values.integrationTests.labels }}
    {{- toYaml .Values.integrationTests.labels | nindent 4 }}
  {{- end }}
  {{- if .Values.integrationTests.annotations }}
  annotations:
    {{- toYaml .Values.integrationTests.annotations | nindent 4 }}
  {{- end }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - secrets
      - configmaps
    verbs:
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - delete
  - apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
      - statefulsets/scale
      - deployments/scale
      - daemonsets
    verbs:
      - get
      - list
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - create
      - delete
{{- end }}
