{{- if .Values.integrationTests.install }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.integrationTests.service.name }}-secret
  labels:
    app.kubernetes.io/name: {{ .Values.integrationTests.service.name }}-secret
    app.kubernetes.io/component: integration-tests
    app.kubernetes.io/part-of: logging
  {{- if .Values.integrationTests.labels }}
    {{- toYaml .Values.integrationTests.labels | nindent 4 }}
  {{- end }}
  {{- if .Values.integrationTests.annotations }}
  annotations:
    {{- toYaml .Values.integrationTests.annotations | nindent 4 }}
  {{- end }}
stringData:
  graylog-user: "{{ .Values.graylog.user }}"
  graylog-password: "{{ .Values.graylog.password }}"
  vm-user: {{ .Values.integrationTests.vmUser | default "" | quote }}
  ssh-key: {{ .Values.integrationTests.sshKey | default "" | quote }}
{{- end }}
