{{- if .Values.integrationTests.install }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.integrationTests.service.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.integrationTests.service.name }}
    app.kubernetes.io/component: integration-tests
    app.kubernetes.io/part-of: logging
  {{- if .Values.integrationTests.labels }}
    {{- toYaml .Values.integrationTests.labels | nindent 4 }}
  {{- end }}
  {{- if .Values.integrationTests.annotations }}
  annotations:
    {{- toYaml .Values.integrationTests.annotations | nindent 4 }}
  {{- end }}
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ .Values.integrationTests.service.name }}
{{- end }}
