{{- if .Values.integrationTests.install }}
{{- if .Values.integrationTests.statusWriting.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: logging-operator-tests-write-status
  labels:
    app.kubernetes.io/name: logging-operator-tests-write-status
    app.kubernetes.io/component: integration-tests
    app.kubernetes.io/part-of: logging
  {{- if .Values.integrationTests.labels }}
    {{- toYaml .Values.integrationTests.labels | nindent 4 }}
  {{- end }}
  {{- if .Values.integrationTests.annotations }}
  annotations:
    {{- toYaml .Values.integrationTests.annotations | nindent 4 }}
  {{- end }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.integrationTests.service.name }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: logging-operator-tests-write-status
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
